name: Deploy Medic Launch React App CI

on:
    push:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies and build
      run: |
        npm ci
        CI=false npm run build
        
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name mediclaunchdb --auth-mode key --destination '$web' --pattern './build/*' --source ./build

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
