name: Deploy Medic Launch React App CI

on:
    push:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name mediclaunchdb --auth-mode key -d '$web' -s build -d \$web

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
